//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFWSFEAFIPTezecoop.DataModeldbSG2000
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSG2000Entities : DbContext
    {
        public dbSG2000Entities()
            : base("name=dbSG2000Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Comprobantes> TB_Comprobantes { get; set; }
        public virtual DbSet<TB_ComprobantesDetalle> TB_ComprobantesDetalle { get; set; }
        public virtual DbSet<TB_Cupones> TB_Cupones { get; set; }
    }
}
