//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFWSFEAFIPTezecoop.DataModeldbSG2000
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_comprobanteAFIP
    {
        public int cod_tipo_comprobante { get; set; }
        public string Descripción { get; set; }
        public string tpComprobante { get; set; }
        public string tpLetra { get; set; }
    }
}
