//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFWSFEAFIPTezecoop.DataModelFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class condicion_iva
    {
        public condicion_iva()
        {
            this.detalle_iva = new HashSet<detalle_iva>();
        }
    
        public int codigo { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<detalle_iva> detalle_iva { get; set; }
    }
}
