/* 
    SQL Manager 2005 Lite for MySQL
    SQL Editor queries
 */

/*  Page 1  */

-- cambios de DML version 1.3 - MySQL

use dbSG2000;

Update   `tb_sincronizacion` SET `dtUltSincrozacion`=NULL;

delete from  tb_cupones;
delete from `tb_comprobantesdetalle`;
delete from `tb_comprobantes`;
delete from `tb_cajas`;
delete FROM  `tb_clientes`;
delete FROM  tb_usuarios;
delete FROM  tb_comisiones;
delete FROM  tb_productos;
delete FROM  tb_Proveedores;
delete FROM  tb_conceptos;
delete FROM  tb_puestos;
delete FROM  tb_logs;





/*  Page 2  */




