'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17929
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ar.gov.afip.wsaa
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LoginFault", [Namespace]:="https://wsaa.afip.gov.ar/ws/services/LoginCms"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LoginFault
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="https://wsaa.afip.gov.ar/ws/services/LoginCms", ConfigurationName:="ar.gov.afip.wsaa.LoginCMS")>  _
    Public Interface LoginCMS
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (http://wsaa.view.sua.dvadac.desein.afip.gov) del mensaje loginCmsRequest no coincide con el valor predeterminado (https://wsaa.afip.gov.ar/ws/services/LoginCms)
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ar.gov.afip.wsaa.LoginFault), Action:="", Name:="fault")>  _
        Function loginCms(ByVal request As ar.gov.afip.wsaa.loginCmsRequest) As ar.gov.afip.wsaa.loginCmsResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="loginCms", WrapperNamespace:="http://wsaa.view.sua.dvadac.desein.afip.gov", IsWrapped:=true)>  _
    Partial Public Class loginCmsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wsaa.view.sua.dvadac.desein.afip.gov", Order:=0)>  _
        Public in0 As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal in0 As String)
            MyBase.New
            Me.in0 = in0
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="loginCmsResponse", WrapperNamespace:="http://wsaa.view.sua.dvadac.desein.afip.gov", IsWrapped:=true)>  _
    Partial Public Class loginCmsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://wsaa.view.sua.dvadac.desein.afip.gov", Order:=0)>  _
        Public loginCmsReturn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal loginCmsReturn As String)
            MyBase.New
            Me.loginCmsReturn = loginCmsReturn
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface LoginCMSChannel
        Inherits ar.gov.afip.wsaa.LoginCMS, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class LoginCMSClient
        Inherits System.ServiceModel.ClientBase(Of ar.gov.afip.wsaa.LoginCMS)
        Implements ar.gov.afip.wsaa.LoginCMS
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ar_gov_afip_wsaa_LoginCMS_loginCms(ByVal request As ar.gov.afip.wsaa.loginCmsRequest) As ar.gov.afip.wsaa.loginCmsResponse Implements ar.gov.afip.wsaa.LoginCMS.loginCms
            Return MyBase.Channel.loginCms(request)
        End Function
        
        Public Function loginCms(ByVal in0 As String) As String
            Dim inValue As ar.gov.afip.wsaa.loginCmsRequest = New ar.gov.afip.wsaa.loginCmsRequest()
            inValue.in0 = in0
            Dim retVal As ar.gov.afip.wsaa.loginCmsResponse = CType(Me,ar.gov.afip.wsaa.LoginCMS).loginCms(inValue)
            Return retVal.loginCmsReturn
        End Function
    End Class
End Namespace
