VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "CImputaciones"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit


Public nrCajaPuesto As String

' version 2.5
Public Function realizarImputacionCajaPuesto() As String

    ' Verificar si la caja esta aprobada por el usuario de la administración
    ' la imputacion de la caja es atomica todo o nada

End Function



