'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17929
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o recompile su proyecto de VS.
'''<summary>
'''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Resources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FacturaElectronicaWS.Resources", GetType(Resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property _Next() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("_Next", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property agregar_editar_icono_6607_96() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("agregar_editar_icono_6607_96", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property anadir_mas_verde_icono_6162_128() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("anadir_mas_verde_icono_6162_128", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property anadir_mas_verde_icono_6162_32() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("anadir_mas_verde_icono_6162_32", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property barra_01_da() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("barra_01_da", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property barra_01_g() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("barra_01_g", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property barra_01_go() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("barra_01_go", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property barra_02_da() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("barra_02_da", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property barra_02_g() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("barra_02_g", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property barra_02_go() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("barra_02_go", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property barra_03_da() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("barra_03_da", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property barra_03_g() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("barra_03_g", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property barra_03_go() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("barra_03_go", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property bbtb_Tr_green() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("bbtb_Tr_green", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
    '''</summary>
    Friend Shared ReadOnly Property busqueda_ico() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("busqueda_ico", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Configuracion() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Configuracion", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Configuracion_h() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Configuracion_h", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
    '''</summary>
    Friend Shared ReadOnly Property Documento_ico() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("Documento_ico", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
    '''</summary>
    Friend Shared ReadOnly Property Ejecutar() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("Ejecutar", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
    '''</summary>
    Friend Shared ReadOnly Property Ejecutar_2() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("Ejecutar_2", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Exit_021() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Exit_021", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property folder_01_o() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("folder_01_o", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property folder_02_c() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("folder_02_c", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property folder_02_h() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("folder_02_h", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property folder_02_l() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("folder_02_l", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property folder_02_o() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("folder_02_o", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property folder_02_oh() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("folder_02_oh", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property ICONO_empresa() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ICONO_empresa", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Mediciones() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Mediciones", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Mediciones_h() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Mediciones_h", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property procesos() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("procesos", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property procesos_h() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("procesos_h", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Refresh_icon_4() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Refresh-icon_4", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property treeview_01() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("treeview_01", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property treeview_02() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("treeview_02", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Class
