//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSG2000Entities : DbContext
    {
        public dbSG2000Entities()
            : base("name=dbSG2000Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Conceptos> TB_Conceptos { get; set; }
        public virtual DbSet<TB_Conciliacion> TB_Conciliacion { get; set; }
        public virtual DbSet<TB_ConciliacionDetalle> TB_ConciliacionDetalle { get; set; }
        public virtual DbSet<TB_ConciliaTarjertas> TB_ConciliaTarjertas { get; set; }
        public virtual DbSet<TB_Cupones> TB_Cupones { get; set; }
        public virtual DbSet<TB_MovimientosContables> TB_MovimientosContables { get; set; }
        public virtual DbSet<TB_MovimientosContablesPosdatados> TB_MovimientosContablesPosdatados { get; set; }
        public virtual DbSet<TB_Parametros> TB_Parametros { get; set; }
        public virtual DbSet<TB_PresentacionesCAI> TB_PresentacionesCAI { get; set; }
        public virtual DbSet<TB_PresentacionesCAIDetalle> TB_PresentacionesCAIDetalle { get; set; }
        public virtual DbSet<TB_Productos> TB_Productos { get; set; }
        public virtual DbSet<TB_Usuarios> TB_Usuarios { get; set; }
        public virtual DbSet<TB_ArchivoTarjeta> TB_ArchivoTarjeta { get; set; }
        public virtual DbSet<TB_ArchivoTarjetaDetalle> TB_ArchivoTarjetaDetalle { get; set; }
    }
}
