//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ConciliaTarjertas
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dtConciliacion { get; set; }
        public string dsUsuario { get; set; }
        public string estado_registro { get; set; }
        public Nullable<System.DateTime> dtinsercion { get; set; }
    }
}
