//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Parametros
    {
        public string dsParametro { get; set; }
        public string vlParametro { get; set; }
        public string tpParametro { get; set; }
        public Nullable<int> nrTamanio { get; set; }
        public Nullable<System.DateTime> dtActualizacion { get; set; }
        public string grupo_parametro { get; set; }
        public string observacion { get; set; }
        public Nullable<bool> flEditable { get; set; }
    }
}
