//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFWSFEAFIPTezecoop
{
    using System;
    using System.Collections.Generic;
    
    public partial class cbtesasoc
    {
        public int idsolicitud { get; set; }
        public int Tipo { get; set; }
        public int PtoVta { get; set; }
        public decimal Nro { get; set; }
    
        public virtual comprobantes_ml comprobantes_ml { get; set; }
        public virtual tipo_comprobante tipo_comprobante { get; set; }
    }
}
