//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFWSFEAFIPTezecoop
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmpasociados
    {
        public int idsolicitud { get; set; }
        public decimal ptovtaasoc { get; set; }
        public decimal nroasoc { get; set; }
        public string Cbte_tipo { get; set; }
    
        public virtual comprobante comprobante { get; set; }
    }
}
