//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFWSFEAFIPTezecoop
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapeo_comprobantes
    {
        public string cod_doc_magma { get; set; }
        public int nro_serie_magma { get; set; }
        public string cod_doc_magma_afip { get; set; }
        public int nro_serie_afip { get; set; }
    }
}
