//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantillas_excel
    {
        public plantillas_excel()
        {
            this.plantillas_excel_detalle = new HashSet<plantillas_excel_detalle>();
        }
    
        public int idplantilla { get; set; }
        public string aplicacion { get; set; }
        public string nombre { get; set; }
        public string hoja_xls { get; set; }
        public string ruta_archivo { get; set; }
        public Nullable<int> fila_datos { get; set; }
        public Nullable<int> columas { get; set; }
        public Nullable<int> filas { get; set; }
        public string base_destino { get; set; }
        public string procedimiento { get; set; }
        public string carp_archivo_tmp { get; set; }
        public string separador { get; set; }
    
        public virtual ICollection<plantillas_excel_detalle> plantillas_excel_detalle { get; set; }
    }
}
