//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Productos
    {
        public int cdProducto { get; set; }
        public string dsProducto { get; set; }
        public Nullable<double> vlPrecioViaje { get; set; }
        public Nullable<double> vlPrecioPeaje { get; set; }
        public string obsHoras { get; set; }
        public Nullable<int> vlPorcentaje { get; set; }
        public string tpOperacion { get; set; }
        public bool flMuestra { get; set; }
        public string cdOrden { get; set; }
        public Nullable<double> vlPrecioViajeSinPeaje { get; set; }
        public Nullable<double> vlKilometros { get; set; }
        public Nullable<System.DateTime> dtActualizacion { get; set; }
        public Nullable<bool> flEliminar { get; set; }
        public Nullable<double> vlPrecioxKilometro { get; set; }
        public Nullable<bool> flMuestraenlaWEB { get; set; }
        public Nullable<bool> flIncluyeComisionRetorno { get; set; }
        public string tpDestino { get; set; }
        public Nullable<int> cdComision { get; set; }
    }
}
