//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ArchivoTarjetaDetalle
    {
        public long Id { get; set; }
        public Nullable<int> idarchivo { get; set; }
        public Nullable<System.DateTime> fechaPresentacion { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<System.DateTime> fechaPago { get; set; }
        public string tarjeta { get; set; }
        public string comprobante { get; set; }
        public string moneda { get; set; }
        public string contenido { get; set; }
        public Nullable<System.DateTime> dtInsercion { get; set; }
    
        public virtual TB_ArchivoTarjeta TB_ArchivoTarjeta { get; set; }
    }
}
