//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ConciliacionDetalle
    {
        public int IdConciliacion { get; set; }
        public decimal nrCupon { get; set; }
        public Nullable<long> IdArchivoTarjetaDetalle { get; set; }
        public Nullable<System.DateTime> fechaPago { get; set; }
    
        public virtual TB_ArchivoTarjetaDetalle TB_ArchivoTarjetaDetalle { get; set; }
        public virtual TB_Conciliacion TB_Conciliacion { get; set; }
    }
}
