//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Conceptos
    {
        public int cdConcepto { get; set; }
        public string tpConcepto { get; set; }
        public string dsConcepto { get; set; }
        public Nullable<double> vlConcepto { get; set; }
        public string tpOperacion { get; set; }
        public Nullable<System.DateTime> dtActualizacion { get; set; }
        public Nullable<bool> flEliminar { get; set; }
        public string tpCajaImputacion { get; set; }
        public string tpCreadoPor { get; set; }
        public Nullable<bool> flSumaenCajaAdm { get; set; }
        public Nullable<bool> flSumaenCajaCooperativa { get; set; }
        public Nullable<bool> flSumaenCajaLicenciatarios { get; set; }
        public Nullable<bool> flOcultadoenCajaAdm { get; set; }
        public Nullable<bool> flOcultadoCajaLicenciatario { get; set; }
        public Nullable<bool> flOcultadoCajaCooperativa { get; set; }
        public Nullable<bool> flOcultadoenRegistracion { get; set; }
    }
}
