//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Clientes
    {
        public int cdCliente { get; set; }
        public string tpCliente { get; set; }
        public string nmNombre { get; set; }
        public string nmApellido { get; set; }
        public string dsRazonSocial { get; set; }
        public string dsDomicilio { get; set; }
        public string cdPostal { get; set; }
        public string nmLocalidad { get; set; }
        public string nrTel { get; set; }
        public string nrFax { get; set; }
        public string dsCargo { get; set; }
        public string dsEmail { get; set; }
        public Nullable<System.DateTime> dtAlta { get; set; }
        public Nullable<System.DateTime> dtBaja { get; set; }
        public string tpDoc { get; set; }
        public string nrDoc { get; set; }
        public string tpIIBB { get; set; }
        public Nullable<decimal> nrIIBB { get; set; }
        public string dsLetraII { get; set; }
        public Nullable<double> vlOrdenanza3337 { get; set; }
        public Nullable<System.DateTime> dtFinOrdenanza { get; set; }
        public bool flBloqueado { get; set; }
        public string tpEstado { get; set; }
        public Nullable<double> vlTopeCredito { get; set; }
        public Nullable<double> vlSaldo { get; set; }
        public string tpIVA { get; set; }
        public Nullable<System.DateTime> dtActualizacion { get; set; }
        public Nullable<bool> flEliminar { get; set; }
        public string tpFormadePago { get; set; }
        public Nullable<short> nrPuesto { get; set; }
    }
}
