//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_numeradores
    {
        public string numerador { get; set; }
        public string nombre { get; set; }
        public string notas { get; set; }
        public int valor_asignado { get; set; }
        public Nullable<int> valor_defecto { get; set; }
        public short incremento { get; set; }
        public string consecutivos { get; set; }
        public string modificable { get; set; }
        public string usuario_mod { get; set; }
        public System.DateTime fecha_mod { get; set; }
        public string terminal_mod { get; set; }
        public string operacion_mod { get; set; }
        public string estado_registro { get; set; }
        public string formulario { get; set; }
        public string seccion { get; set; }
        public string bloque { get; set; }
        public short linea { get; set; }
    }
}
