//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ObligacionesCuotas
    {
        public int nro_trans { get; set; }
        public int cod_tit { get; set; }
        public int nro_cuota { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public Nullable<decimal> importe { get; set; }
        public string nrLicencia { get; set; }
        public string comentarios { get; set; }
    }
}
