//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PresentacionesCAI
    {
        public TB_PresentacionesCAI()
        {
            this.TB_PresentacionesCAIDetalle = new HashSet<TB_PresentacionesCAIDetalle>();
        }
    
        public int IdPresentacion { get; set; }
        public Nullable<int> nrAnio { get; set; }
        public Nullable<int> nrMes { get; set; }
        public Nullable<System.DateTime> dtPresentacion { get; set; }
        public string dsUsuario { get; set; }
        public string flestado { get; set; }
        public Nullable<System.DateTime> dtModificacion { get; set; }
    
        public virtual ICollection<TB_PresentacionesCAIDetalle> TB_PresentacionesCAIDetalle { get; set; }
    }
}
