//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Proveedores
    {
        public int cdProveedor { get; set; }
        public string nrSocio { get; set; }
        public string tpCategoria { get; set; }
        public string nmNombre { get; set; }
        public string nmApellido { get; set; }
        public string dsRazonSocial { get; set; }
        public string dsDomicilio { get; set; }
        public string cdPostal { get; set; }
        public string nmLocalidad { get; set; }
        public string nrTel { get; set; }
        public string nrFax { get; set; }
        public string dsCargo { get; set; }
        public string dsEmail { get; set; }
        public Nullable<System.DateTime> dtAlta { get; set; }
        public Nullable<System.DateTime> dtBaja { get; set; }
        public Nullable<short> tpIVA { get; set; }
        public string nrCUIT { get; set; }
        public string tpIIBB { get; set; }
        public Nullable<double> nrIIBB { get; set; }
        public Nullable<double> vlOrdenanza3337 { get; set; }
        public Nullable<System.DateTime> dtFinOrdenanza { get; set; }
        public bool flBloqueado { get; set; }
        public string tpEstado { get; set; }
        public string nrLicencia { get; set; }
        public Nullable<System.DateTime> dtActualizacion { get; set; }
        public Nullable<bool> flEliminar { get; set; }
        public string tpmodeloauto { get; set; }
        public Nullable<bool> flcongas { get; set; }
        public string chofer1 { get; set; }
        public string chofer2 { get; set; }
        public string chofer3 { get; set; }
        public string telchofer1 { get; set; }
        public string telchofer2 { get; set; }
        public string telchofer3 { get; set; }
    }
}
