//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_transCab
    {
        public string cod_emp { get; set; }
        public int cod_tit { get; set; }
        public string letra_doc { get; set; }
        public System.DateTime fec_valor { get; set; }
        public string com_mov { get; set; }
        public string cod_moneda_ing { get; set; }
        public Nullable<decimal> tc_ing { get; set; }
        public Nullable<decimal> imp_subtot_ing { get; set; }
        public Nullable<decimal> imp_ivatot_ing { get; set; }
        public Nullable<decimal> imp_tot_ing { get; set; }
        public Nullable<int> nro_int { get; set; }
        public int nro_trans { get; set; }
        public string cod_doc { get; set; }
        public int nro_doc { get; set; }
        public System.DateTime fec_doc { get; set; }
        public short serie_doc { get; set; }
        public string formulario { get; set; }
        public string seccion { get; set; }
        public string bloque { get; set; }
        public short linea { get; set; }
        public string usuario_mod { get; set; }
        public System.DateTime fecha_mod { get; set; }
        public string terminal_mod { get; set; }
        public string operacion_mod { get; set; }
        public string estado_registro { get; set; }
        public Nullable<short> cuotas { get; set; }
        public string periodo { get; set; }
    }
}
