//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.36392
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGLibrary_WSTest.WSTezecoop {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Obligaciones", Namespace="http://schemas.datacontract.org/2004/07/SGLibrary.Services")]
    [System.SerializableAttribute()]
    public partial class Obligaciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGLibrary_WSTest.WSTezecoop.TB_ObligacionesCuotas[] TB_ObligacionesCuotasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGLibrary_WSTest.WSTezecoop.TB_ObligacionesTitulares[] TB_ObligacionesTitularesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SGLibrary_WSTest.WSTezecoop.TB_transCab TB_transCabField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGLibrary_WSTest.WSTezecoop.TB_ObligacionesCuotas[] TB_ObligacionesCuotas {
            get {
                return this.TB_ObligacionesCuotasField;
            }
            set {
                if ((object.ReferenceEquals(this.TB_ObligacionesCuotasField, value) != true)) {
                    this.TB_ObligacionesCuotasField = value;
                    this.RaisePropertyChanged("TB_ObligacionesCuotas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGLibrary_WSTest.WSTezecoop.TB_ObligacionesTitulares[] TB_ObligacionesTitulares {
            get {
                return this.TB_ObligacionesTitularesField;
            }
            set {
                if ((object.ReferenceEquals(this.TB_ObligacionesTitularesField, value) != true)) {
                    this.TB_ObligacionesTitularesField = value;
                    this.RaisePropertyChanged("TB_ObligacionesTitulares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGLibrary_WSTest.WSTezecoop.TB_transCab TB_transCab {
            get {
                return this.TB_transCabField;
            }
            set {
                if ((object.ReferenceEquals(this.TB_transCabField, value) != true)) {
                    this.TB_transCabField = value;
                    this.RaisePropertyChanged("TB_transCab");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_transCab", Namespace="http://schemas.datacontract.org/2004/07/SGLibrary")]
    [System.SerializableAttribute()]
    public partial class TB_transCab : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bloqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_docField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_empField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_moneda_ingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_titField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string com_movField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> cuotasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estado_registroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fec_docField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fec_valorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_modField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string formularioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> imp_ivatot_ingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> imp_subtot_ingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> imp_tot_ingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string letra_docField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short lineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nro_docField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> nro_intField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nro_transField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string operacion_modField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string periodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string seccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short serie_docField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> tc_ingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string terminal_modField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuario_modField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bloque {
            get {
                return this.bloqueField;
            }
            set {
                if ((object.ReferenceEquals(this.bloqueField, value) != true)) {
                    this.bloqueField = value;
                    this.RaisePropertyChanged("bloque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_doc {
            get {
                return this.cod_docField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_docField, value) != true)) {
                    this.cod_docField = value;
                    this.RaisePropertyChanged("cod_doc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_emp {
            get {
                return this.cod_empField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_empField, value) != true)) {
                    this.cod_empField = value;
                    this.RaisePropertyChanged("cod_emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_moneda_ing {
            get {
                return this.cod_moneda_ingField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_moneda_ingField, value) != true)) {
                    this.cod_moneda_ingField = value;
                    this.RaisePropertyChanged("cod_moneda_ing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_tit {
            get {
                return this.cod_titField;
            }
            set {
                if ((this.cod_titField.Equals(value) != true)) {
                    this.cod_titField = value;
                    this.RaisePropertyChanged("cod_tit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string com_mov {
            get {
                return this.com_movField;
            }
            set {
                if ((object.ReferenceEquals(this.com_movField, value) != true)) {
                    this.com_movField = value;
                    this.RaisePropertyChanged("com_mov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> cuotas {
            get {
                return this.cuotasField;
            }
            set {
                if ((this.cuotasField.Equals(value) != true)) {
                    this.cuotasField = value;
                    this.RaisePropertyChanged("cuotas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado_registro {
            get {
                return this.estado_registroField;
            }
            set {
                if ((object.ReferenceEquals(this.estado_registroField, value) != true)) {
                    this.estado_registroField = value;
                    this.RaisePropertyChanged("estado_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fec_doc {
            get {
                return this.fec_docField;
            }
            set {
                if ((this.fec_docField.Equals(value) != true)) {
                    this.fec_docField = value;
                    this.RaisePropertyChanged("fec_doc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fec_valor {
            get {
                return this.fec_valorField;
            }
            set {
                if ((this.fec_valorField.Equals(value) != true)) {
                    this.fec_valorField = value;
                    this.RaisePropertyChanged("fec_valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_mod {
            get {
                return this.fecha_modField;
            }
            set {
                if ((this.fecha_modField.Equals(value) != true)) {
                    this.fecha_modField = value;
                    this.RaisePropertyChanged("fecha_mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string formulario {
            get {
                return this.formularioField;
            }
            set {
                if ((object.ReferenceEquals(this.formularioField, value) != true)) {
                    this.formularioField = value;
                    this.RaisePropertyChanged("formulario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> imp_ivatot_ing {
            get {
                return this.imp_ivatot_ingField;
            }
            set {
                if ((this.imp_ivatot_ingField.Equals(value) != true)) {
                    this.imp_ivatot_ingField = value;
                    this.RaisePropertyChanged("imp_ivatot_ing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> imp_subtot_ing {
            get {
                return this.imp_subtot_ingField;
            }
            set {
                if ((this.imp_subtot_ingField.Equals(value) != true)) {
                    this.imp_subtot_ingField = value;
                    this.RaisePropertyChanged("imp_subtot_ing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> imp_tot_ing {
            get {
                return this.imp_tot_ingField;
            }
            set {
                if ((this.imp_tot_ingField.Equals(value) != true)) {
                    this.imp_tot_ingField = value;
                    this.RaisePropertyChanged("imp_tot_ing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string letra_doc {
            get {
                return this.letra_docField;
            }
            set {
                if ((object.ReferenceEquals(this.letra_docField, value) != true)) {
                    this.letra_docField = value;
                    this.RaisePropertyChanged("letra_doc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short linea {
            get {
                return this.lineaField;
            }
            set {
                if ((this.lineaField.Equals(value) != true)) {
                    this.lineaField = value;
                    this.RaisePropertyChanged("linea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nro_doc {
            get {
                return this.nro_docField;
            }
            set {
                if ((this.nro_docField.Equals(value) != true)) {
                    this.nro_docField = value;
                    this.RaisePropertyChanged("nro_doc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> nro_int {
            get {
                return this.nro_intField;
            }
            set {
                if ((this.nro_intField.Equals(value) != true)) {
                    this.nro_intField = value;
                    this.RaisePropertyChanged("nro_int");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nro_trans {
            get {
                return this.nro_transField;
            }
            set {
                if ((this.nro_transField.Equals(value) != true)) {
                    this.nro_transField = value;
                    this.RaisePropertyChanged("nro_trans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string operacion_mod {
            get {
                return this.operacion_modField;
            }
            set {
                if ((object.ReferenceEquals(this.operacion_modField, value) != true)) {
                    this.operacion_modField = value;
                    this.RaisePropertyChanged("operacion_mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string periodo {
            get {
                return this.periodoField;
            }
            set {
                if ((object.ReferenceEquals(this.periodoField, value) != true)) {
                    this.periodoField = value;
                    this.RaisePropertyChanged("periodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string seccion {
            get {
                return this.seccionField;
            }
            set {
                if ((object.ReferenceEquals(this.seccionField, value) != true)) {
                    this.seccionField = value;
                    this.RaisePropertyChanged("seccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short serie_doc {
            get {
                return this.serie_docField;
            }
            set {
                if ((this.serie_docField.Equals(value) != true)) {
                    this.serie_docField = value;
                    this.RaisePropertyChanged("serie_doc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> tc_ing {
            get {
                return this.tc_ingField;
            }
            set {
                if ((this.tc_ingField.Equals(value) != true)) {
                    this.tc_ingField = value;
                    this.RaisePropertyChanged("tc_ing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string terminal_mod {
            get {
                return this.terminal_modField;
            }
            set {
                if ((object.ReferenceEquals(this.terminal_modField, value) != true)) {
                    this.terminal_modField = value;
                    this.RaisePropertyChanged("terminal_mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario_mod {
            get {
                return this.usuario_modField;
            }
            set {
                if ((object.ReferenceEquals(this.usuario_modField, value) != true)) {
                    this.usuario_modField = value;
                    this.RaisePropertyChanged("usuario_mod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_ObligacionesCuotas", Namespace="http://schemas.datacontract.org/2004/07/SGLibrary")]
    [System.SerializableAttribute()]
    public partial class TB_ObligacionesCuotas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_titField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string comentariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fecha_vencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> importeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nrLicenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nro_cuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nro_transField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_tit {
            get {
                return this.cod_titField;
            }
            set {
                if ((this.cod_titField.Equals(value) != true)) {
                    this.cod_titField = value;
                    this.RaisePropertyChanged("cod_tit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comentarios {
            get {
                return this.comentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.comentariosField, value) != true)) {
                    this.comentariosField = value;
                    this.RaisePropertyChanged("comentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha_vencimiento {
            get {
                return this.fecha_vencimientoField;
            }
            set {
                if ((this.fecha_vencimientoField.Equals(value) != true)) {
                    this.fecha_vencimientoField = value;
                    this.RaisePropertyChanged("fecha_vencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> importe {
            get {
                return this.importeField;
            }
            set {
                if ((this.importeField.Equals(value) != true)) {
                    this.importeField = value;
                    this.RaisePropertyChanged("importe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nrLicencia {
            get {
                return this.nrLicenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.nrLicenciaField, value) != true)) {
                    this.nrLicenciaField = value;
                    this.RaisePropertyChanged("nrLicencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nro_cuota {
            get {
                return this.nro_cuotaField;
            }
            set {
                if ((this.nro_cuotaField.Equals(value) != true)) {
                    this.nro_cuotaField = value;
                    this.RaisePropertyChanged("nro_cuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nro_trans {
            get {
                return this.nro_transField;
            }
            set {
                if ((this.nro_transField.Equals(value) != true)) {
                    this.nro_transField = value;
                    this.RaisePropertyChanged("nro_trans");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_ObligacionesTitulares", Namespace="http://schemas.datacontract.org/2004/07/SGLibrary")]
    [System.SerializableAttribute()]
    public partial class TB_ObligacionesTitulares : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_titField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nmApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nmNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nrLicenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nrTelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nro_transField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_tit {
            get {
                return this.cod_titField;
            }
            set {
                if ((this.cod_titField.Equals(value) != true)) {
                    this.cod_titField = value;
                    this.RaisePropertyChanged("cod_tit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nmApellido {
            get {
                return this.nmApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.nmApellidoField, value) != true)) {
                    this.nmApellidoField = value;
                    this.RaisePropertyChanged("nmApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nmNombre {
            get {
                return this.nmNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nmNombreField, value) != true)) {
                    this.nmNombreField = value;
                    this.RaisePropertyChanged("nmNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nrLicencia {
            get {
                return this.nrLicenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.nrLicenciaField, value) != true)) {
                    this.nrLicenciaField = value;
                    this.RaisePropertyChanged("nrLicencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nrTelefono {
            get {
                return this.nrTelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.nrTelefonoField, value) != true)) {
                    this.nrTelefonoField = value;
                    this.RaisePropertyChanged("nrTelefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nro_trans {
            get {
                return this.nro_transField;
            }
            set {
                if ((this.nro_transField.Equals(value) != true)) {
                    this.nro_transField = value;
                    this.RaisePropertyChanged("nro_trans");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSTezecoop.IWSObligaciones")]
    public interface IWSObligaciones {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSObligaciones/obtenerObligacionxId", ReplyAction="http://tempuri.org/IWSObligaciones/obtenerObligacionxIdResponse")]
        SGLibrary_WSTest.WSTezecoop.Obligaciones obtenerObligacionxId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSObligaciones/obtenerObligacionxId", ReplyAction="http://tempuri.org/IWSObligaciones/obtenerObligacionxIdResponse")]
        System.Threading.Tasks.Task<SGLibrary_WSTest.WSTezecoop.Obligaciones> obtenerObligacionxIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSObligaciones/Saludar", ReplyAction="http://tempuri.org/IWSObligaciones/SaludarResponse")]
        string Saludar(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSObligaciones/Saludar", ReplyAction="http://tempuri.org/IWSObligaciones/SaludarResponse")]
        System.Threading.Tasks.Task<string> SaludarAsync(string nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSObligacionesChannel : SGLibrary_WSTest.WSTezecoop.IWSObligaciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSObligacionesClient : System.ServiceModel.ClientBase<SGLibrary_WSTest.WSTezecoop.IWSObligaciones>, SGLibrary_WSTest.WSTezecoop.IWSObligaciones {
        
        public WSObligacionesClient() {
        }
        
        public WSObligacionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSObligacionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSObligacionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSObligacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SGLibrary_WSTest.WSTezecoop.Obligaciones obtenerObligacionxId() {
            return base.Channel.obtenerObligacionxId();
        }
        
        public System.Threading.Tasks.Task<SGLibrary_WSTest.WSTezecoop.Obligaciones> obtenerObligacionxIdAsync() {
            return base.Channel.obtenerObligacionxIdAsync();
        }
        
        public string Saludar(string nombre) {
            return base.Channel.Saludar(nombre);
        }
        
        public System.Threading.Tasks.Task<string> SaludarAsync(string nombre) {
            return base.Channel.SaludarAsync(nombre);
        }
    }
}
